Update IDEA to 2024.3 (#2)
* chore: migrate to idea 2024.3 and update deps

* fix: exclude `output:` path for documentSymbol

* fix: NPE in textDocument/hover

* fix: IllegalStateException incompletion

Request completionItem/resolve failed.
  Message: Internal error.
  Code: -32603
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.IllegalStateException: Override this or documentationTargets(Editor, PsiFile, LookupElement)

* fix: IllegalArgumentException incompletion

Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'lookupElementsWithMatchers' of org/rri/ideals/server/completions/CompletionService.convertLookupElementsWithMatcherToCompletionItems must not be null

* fix: PythonCore version imcompatible

* fix tests

* fix: invalid usage of IdeDocumentationTargetProvider

* fix: workspace symbol not working for .kt file

* fix: code action

* fix: exclude inject language code action

* fix: diagnostics changed in 2024.3

* fix: use Optional.ofNullable for nullable value

* fix tests

* fix: Scope cannot be cancelled because it does not have a job

* fix: remove unnecessary symbol sorting

* fix test

* fix test

* fix test

TraceableDisposable$DisposalException: Editor EditorImpl[{fileName} (invalid, reason: File deleted: VfsEvent[deleted: {filePath}])] hasn't been released

* fix: force daemon analyzer started

* chore: remove unnecessary file

* fix test

* refactor

* test: make assertion relaxed for kotlin symbols (for now)

* Revert "fix: force daemon analyzer started"

This reverts commit 0d385c12bad22bf4e235f2f7bc223cf68b950c34.

* fix: icon error in STDIO mode

general/inspectionsWarning.svg must be instance of CachedImageIcon (actualClass=class com.intellij.ui.DummyIconImpl)

* fix: EDT problem

This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, or use com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking.